#
# This file contains configuration flags to customize your site
#

title: Jellie Noms

# Name of your site (displayed in the header)
name: Kelly Zhang

# Short bio or description (displayed in the header)
description: >- # this means to ignore newlines until "baseurl:"
  Hi I'm Kelly, and I love food! Original recipes, food hacks and experiments, and discussions about food. All on a student budget.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
# avatar: https://kellyzhang.me/thumbs/favicon2.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook: jelliesbakery
  flickr:
  instagram: jellieeats
  linkedin:
  rss: # just type anything here for a working RSS icon
  twitter:
  youtube: # channel/<your_long_string> or user/<user-name>

# Talkyard comments
talkyard_server_url: https://comments-for-kellyzhang-me.talkyard.net
talkyard_script_url: https://c1.ty-cdn.net/-/talkyard-comments.min.js

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:
disqus-shortname:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:


# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/food"
url: "https://kellyzhang.me/" # the base hostname & protocol for your site, e.g. http://example.com
production_url : https://0100101101011010.github.io/food/
BASE_PATH : https://kellyzhang.me/food/

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: :title/

paginate: 6
paginate_path: /page/:num/


#sidebar
default-image: jellies-bakery-banner.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer


built-by: webjeda

copyright:
   name: kelly zhang
   link: 'https://kellyzhang.me'

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: compressed # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-redirect-from

plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-redirect-from]

include:
  ["_pages"]

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
